// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj7TCAuZEhAGGo25R_FmldfKPV8-1QPD8',
    appId: '1:48837244410:web:bec3d5d4630769c5362043',
    messagingSenderId: '48837244410',
    projectId: 'solex-green-energy',
    authDomain: 'solex-green-energy.firebaseapp.com',
    databaseURL: 'https://solex-green-energy-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'solex-green-energy.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBilZgbyNrjkWCSy5Rdj3PS8uavH-onK0I',
    appId: '1:48837244410:android:5b01b0499227f46a362043',
    messagingSenderId: '48837244410',
    projectId: 'solex-green-energy',
    databaseURL: 'https://solex-green-energy-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'solex-green-energy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHfTNkdsmpmUjJPiwCHcVtGJkvN0e6K5Y',
    appId: '1:48837244410:ios:f583b079246457a7362043',
    messagingSenderId: '48837244410',
    projectId: 'solex-green-energy',
    databaseURL: 'https://solex-green-energy-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'solex-green-energy.appspot.com',
    iosBundleId: 'com.meklint.solex.solex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHfTNkdsmpmUjJPiwCHcVtGJkvN0e6K5Y',
    appId: '1:48837244410:ios:f583b079246457a7362043',
    messagingSenderId: '48837244410',
    projectId: 'solex-green-energy',
    databaseURL: 'https://solex-green-energy-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'solex-green-energy.appspot.com',
    iosBundleId: 'com.meklint.solex.solex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCj7TCAuZEhAGGo25R_FmldfKPV8-1QPD8',
    appId: '1:48837244410:web:88a13f3dcd54f5c8362043',
    messagingSenderId: '48837244410',
    projectId: 'solex-green-energy',
    authDomain: 'solex-green-energy.firebaseapp.com',
    databaseURL: 'https://solex-green-energy-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'solex-green-energy.appspot.com',
  );
}
